#ifndef _ENUMS_H
#define _ENUMS_H
typedef enum
{
    STATE_STANDING = 0,
    STATE_FALL_FLYING = 1,
    STATE_SLEEPING = 2,
    STATE_SWIMMING = 3,
    STATE_SPIN_ATTACK = 4,
    STATE_SNEAKING = 5,
    STATE_LONG_JUMPING = 6,
    STATE_DYING = 7,
    STATE_CROAKING = 8,
    STATE_USING_TONGUE = 9,
    STATE_ROARING = 10,
    STATE_SNIFFING = 11,
    STATE_EMERGING = 12,
    STATE_DIGGING = 13
} State;
typedef enum
{
    ENTITY_DATA_BYTE = 0,
    ENTITY_DATA_INTEGER = 1,
    ENTITY_DATA_LONG = 2,
    ENTITY_DATA_FLOAT = 3,
    ENTITY_DATA_STRING = 4,
    ENTITY_DATA_TEXT_COMPONENT = 5,
    ENTITY_DATA_OPTIONAL_TEXT_COMPONENT = 6,
    ENTITY_DATA_ITEM_STACK = 7,
    ENTITY_DATA_BOOLEAN = 8,
    ENTITY_DATA_ROTATION = 9,
    ENTITY_DATA_VEC3I = 10,
    ENTITY_DATA_OPTIONAL_VEC3I = 11,
    ENTITY_DATA_DIRECTION = 12,
    ENTITY_DATA_OPTIONAL_UUID = 13,
    ENTITY_DATA_BLOCK_STATE = 14,
    ENTITY_DATA_OPTIONAL_BLOCK_STATE = 15,
    ENTITY_DATA_NBT = 16,
    ENTITY_DATA_PARTICLE = 17,
    ENTITY_DATA_VILLAGER_DATA = 18,
    ENTITY_DATA_OPTIONAL_INTEGER = 19,
    ENTITY_DATA_POSE = 20,
    ENTITY_DATA_CAT_VARIANT = 21,
    ENTITY_DATA_FROG_VARIANT = 22,
    ENTITY_DATA_OPTIONAL_GLOBAL_POSITION = 23,
    ENTITY_DATA_MOTIF = 24,
    ENTITY_DATA_SNIFFER_STATE = 25,
    ENTITY_DATA_VEC3F = 26,
    ENTITY_DATA_QUATERNIONF = 27
} EntityDataMetadata;
typedef enum
{
    ENTITY_FLAGS = 0,
    ENTITY_AIR_SUPPLY = 1,
    ENTITY_CUSTOM_NAME = 2,
    ENTITY_CUSTOM_NAME_VISIBLE = 3,
    ENTITY_SILENT = 4,
    ENTITY_NO_GRAVITY = 5,
    ENTITY_POSE = 6,
    ENTITY_TICKS_FROZEN = 7
} EntityMetadata;
typedef enum
{
    PLAYER_ABSORPTION_HEARTS = 15,
    PLAYER_SCORE = 16,
    PLAYER_SKIN_PARTS_FLAGS = 17,
    PLAYER_SKIN_MAIN_HAND = 18,
    PLAYER_LEFT_SHOULDER_DATA = 19,
    PLAYER_RIGHT_SHOULDER_DATA = 20
} PlayerEntityMetadata;
typedef enum
{
    TABLIST_ACTION_ADDPLAYER = (1 << 0),
    TABLIST_ACTION_INITCHAT = (1 << 1),
    TABLIST_ACTION_GAMEMODE = (1 << 2),
    TABLIST_ACTION_LISTED = (1 << 3),
    TABLIST_ACTION_LATENCY = (1 << 4),
    TABLIST_ACTION_NAME = (1 << 5)
} TabListAction;
typedef enum
{
    EVENT_NO_RESPAWN_BLOCK,
    EVENT_BEGIN_RAINING,
    EVENT_END_RAINING,
    EVENT_CHANGE_GAME_MODE,
    EVENT_WIN_GAME,
    EVENT_DEMO,
    EVENT_ARROW_HIT_PLAYER,
    EVENT_RAIN_LEVEL_CHANGE,
    EVENT_THUNDER_LEVEL_CHANGE,
    EVENT_PLAY_PUFFERFISH_SOUND,
    EVENT_ELDER_GURDIAN_APPEARANCE,
    EVENT_RESPAWN_SCREEN,
} GameEvent;
typedef enum
{
    ABILILTIES_INVULNERABLE = (1 << 0),
    ABILILTIES_FLYING = (1 << 1),
    ABILILTIES_CAN_FLY = (1 << 2),
    ABILILTIES_INSTABUILD = (1 << 3),
    ABILILTIES_CLEAR = (1 << 4)
} PlayerAbilities;
#endif